### ISSUE TITLE
Submit a file for malware analysis

### ISSUE THREAD

**Issue by pgagnidze** [Owloops/updo#4]
https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by pgagnidze** [comment]
Similar issue with another tool as an example - https://github.com/sheepla/pingu

**Comment by dominis** [comment]
Hello @pgagnidze, You can solve this by publishing the binaries instead of an tar.gz archive in goreleaser. This is a working config you can check: https://github.com/berbyte/sinkzone/blob/main/.goreleaser.yml
