### ISSUE TITLE
fix version in go.mod

### ISSUE THREAD

**Issue by 13werwolf13** [Owloops/updo#5]
i try build package with updo to opensuse repos. and i get go error:
```shell
[werwolf@home] /tmp/updo (8083840) 
❯ /usr/lib64/go/1.21/bin/go mod vendor
go: errors parsing go.mod:
/tmp/updo/go.mod:3: invalid go version '1.21.5': must match format 1.23
```

if i fix `1.21.5` to `1.21` in `go.mod` file than vendor work normaly.
as i understood this fix should be in uppstream

P.S.: sorry for my bad english

**Comment by pgagnidze** [comment]
@13werwolf13 Thanks for reporting!

Fixed it here https://github.com/Owloops/updo/commit/8cae28e8b6a3a61476abc13476a5e17815cb19e8

**Comment by 13werwolf13** [comment]
now updo is in opensuse tumbleweed and opensuse leap 15.5 in the `home:Werwolf2517` repository

link to the builder: https://build.opensuse.org/package/show/home:Werwolf2517/updo

the installation is like this:
```shell
zypper ar --refresh obs://home:Werwolf2517 home:Werwolf2517
zypper in updo
```

**Comment by pgagnidze** [comment]
@13werwolf13 That sounds great, I appreciate it!
